sudo: required

notifications:
   email: false

language: cpp

services:
  - docker

before_install:
  - docker pull base/devel

script:
# needed for building toolchain only
#  - travis_wait 40 docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
  - travis_wait 60 docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
