language: cpp
sudo: false
notifications:
  email: false
compiler: gcc
addons:
  apt:
    packages:
        - build-essential
        - checkinstall
        - bison
        - flex
        - gettext
        - git
        - mercurial
        - subversion
        - ninja-build
        - gyp
        - cmake
        - yasm
        - nasm
        - automake
        - pkg-config
        - libtool
#        - libtool-bin
        - gcc-multilib
        - g++-multilib
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - libgcrypt-dev
        - gperf
        - ragel
        - texinfo
        - autopoint
        - re2c
        - asciidoc
        - python-docutils
        - rst2pdf
        - docbook2x
        - unzip
        - p7zip-full

install: true
script:
    - ./mpv-build-lite.sh
